### ISSUE TITLE
第一次试运行报错

### ISSUE THREAD

**Issue by hanayashiki** [thunlp/THUTag#3]
```
19/01/20 13:28:59 Cut the dataset into 5 folds.
19/01/20 13:28:59 dataType:DoubanPost
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.simontuffs.onejar.Boot.run(Boot.java:306)
        at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.io.FileNotFoundException: /data/disk1/private/ydm/tryWTM/cut.gz (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:299)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:188)
        at org.thunlp.io.RecordWriter.getOutputStream(RecordWriter.java:116)
        at org.thunlp.io.RecordWriter.<init>(RecordWriter.java:58)
        at org.thunlp.io.RecordWriter.<init>(RecordWriter.java:42)
        at org.thunlp.io.RecordWriter.<init>(RecordWriter.java:38)
        at org.thunlp.tagsuggest.dataset.CutFolds.cutFolds(CutFolds.java:31)
        at org.thunlp.tagsuggest.evaluation.CrossValidator.run(CrossValidator.java:75)
        at org.thunlp.tool.EntryPoint.main(EntryPoint.java:66)
        ... 6 more
```

我用的指令是
```
java -Xmx5G \
    -jar ./tagsuggest.jar evaluation.CrossValidator \
    --dataset=../traindata/bookPost70000.dat \
    --trainer_class=TrainWTM  \
    --suggester_class=SMTTagSuggest \
    --num_folds=5 \
    --config="dataType=DoubanPost;para=0.5;minwordfreq=10;mintagfreq=10;selfTrans=0.2;commonLimit=2" --working_dir=/data/disk1/private/ydm/tryWTM/ --at_n=10 --report=/data/disk1/private/ydm/report/evaluation_WTMreal.txt \
```
目录是`THUTag/build`
是否是因为使用绝对路径引用了什么tool？感谢解答

**Comment by YeDeming** [comment]
试着cd进去giza++ make一下？

**Comment by YeDeming** [comment]
你的运行指令--working_dir=/data/disk1/private/ydm/tryWTM/  这个文件夹要改一下

**Comment by hanayashiki** [comment]
谢谢，我已经跑通了
