### ISSUE TITLE
交叉验证出错看

### ISSUE THREAD

**Issue by sly123197811** [thunlp/THUTag#8]
在demo/下运行：
java -Xmx5G -jar ./tagsuggest.jar evaluation.CrossValidator \
    --dataset=../traindata/bookPost70000.dat \
    --trainer_class=TrainWTM \
    --suggester_class=SMTTagSuggest \
    --num_folds=5 \
    --config="dataType=DoubanPost;para=0.5;minwordfreq=10;mintagfreq=10;selfTrans=0.2;commonLimit=2" \
    --working_dir=./wtm_douban \
    --at_n=10 \
    --report=./evaluation_WTMreal.txt

报以下错误：
java.io.FileNotFoundException: ./wtm_douban/model.0.gz/book.vcb (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:131)
	at java.io.FileInputStream.<init>(FileInputStream.java:87)
	at org.thunlp.tagsuggest.contentbase.SMTTagSuggest.loadModel(SMTTagSuggest.java:72)
	at org.thunlp.tagsuggest.evaluation.CrossValidator.run(CrossValidator.java:99)
	at org.thunlp.tool.EntryPoint.main(EntryPoint.java:66)
请问book.vcb 是自动生成的吗？如果手动生成，我应该从哪里入手，请指教，万分感谢

**Comment by YeDeming** [comment]
应该需要重新make一下giza++

**Comment by sly123197811** [comment]
> 应该需要重新make一下giza++

按照您的方法试了一下，重新make giza++后，把生成的GIZA++、mkcls、plain2snt.out 3个文件在demo/替换了一下，但是还是报相同的错误

**Comment by sly123197811** [comment]
> 应该需要重新make一下giza++
您好，我又试了一下，在model.0.gz/ 下，使用 ./plain2snt.out wtm_douban/model.0.gz/book wtm_douban/model.0.gz/bookTag  生成book.vcb和bookTag.vcb文件，可以跑通代码，扔存在两个问题：
1. 第一次测试，准确率和召回率都为0，Perplexity ：NaN
2. 第一轮测试完毕，开始第二轮的时候，又出现相同的问题，model1.gz中缺少book.vcb

详细输出如下：
20/06/22 16:54:10 loading 355268 states
*.t1.5 not exist
20/06/22 16:54:11 *.t1.5 not exist
20/06/22 16:54:11 0
*.ti.final not exist
20/06/22 16:54:11 *.ti.final not exist
20/06/22 16:54:11 Use cached lexicons
20/06/22 16:54:11 Use cached lexicons
20/06/22 16:54:12 Property 'wordsegment.stopwords.en.file' is not valid, will use default word list instead.
20/06/22 16:54:12 evaluated 0
20/06/22 16:54:12   @5 p:0.0 r: 0.0
20/06/22 16:54:12   Perplexity:NaN
20/06/22 16:54:12 evaluated 100
20/06/22 16:54:12   @5 p:0.0 r: 0.0
20/06/22 16:54:12   Perplexity:NaN
20/06/22 16:54:12 evaluated 200
20/06/22 16:54:12   @5 p:0.0 r: 0.0
20/06/22 16:54:12   Perplexity:NaN
20/06/22 16:54:12 evaluated 300
20/06/22 16:54:12   @5 p:0.0 r: 0.0
20/06/22 16:54:12   Perplexity:NaN
20/06/22 16:54:12 evaluated 400
..........
..........
20/06/22 16:55:26 Testing 1
20/06/22 16:55:26 /root/test/sly/opt/THUTag/demo//chinese_stop_word.txt
20/06/22 16:55:26 loading 355268 states
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.io.FileNotFoundException: ./wtm_douban/model.1.gz/book.vcb (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:131)
	at java.io.FileInputStream.<init>(FileInputStream.java:87)
	at org.thunlp.tagsuggest.contentbase.SMTTagSuggest.loadModel(SMTTagSuggest.java:72)
	at org.thunlp.tagsuggest.evaluation.CrossValidator.run(CrossValidator.java:99)
	at org.thunlp.tool.EntryPoint.main(EntryPoint.java:66)
